### PR TITLE
Display weekdays on the left, not at the top

### PR DESCRIPTION
**Pull request by nerijus**
change white to gray for the days of inactive months
display Saturdays and Sundays red

### CODE REVIEW

**Comment by nerijus** [comment]
It should not be merged as is, because there should be a preference.

**Comment by poroussel** [comment]
Adding a preference for this is a bit of work (the calendar would have to handle preference changes on the fly etc) but what do you say about adding the following commit ?

73771e9c2278271002f8095ddce5bb5b76b31b03

**Comment by nerijus** [comment]
Yes, it is OK, I actually wanted to do it with 'defaults write', but did not know how. Thank you!

**Comment by nerijus** [comment]
Could you please include this PR as well in the new release?

**Comment by poroussel** [comment]
I'll take another look at it and will let you know.

----- Mail original -----

**Comment by nerijus** [comment]
Obsoleted by PR #7.

**Pull request closed without merging**
