### PR TITLE
Nextcloud only accepts ical v2 files

### PR DESCRIPTION
**Pull request by iamleeg**
So without actually changing the ical format, tell it we support v2

### CODE REVIEW

**Comment by iamleeg** [comment]
This partially addresses #4

**Comment by poroussel** [comment]
Have you tested it works with other ical servers ?

**Comment by iamleeg** [comment]
No, not yet. If you have a suite of test servers you often use, please point us at them :)

**Comment by poroussel** [comment]
Well, all those informations disappeared from my memory a long time ago, sorry !

**Pull request merged**
